#
#	$Id: 1b571d75444b6b4b4a959b2a059bf74e4315aca4 $
#
# GU localisation module Makefile
#
BIN=gutexttowbd

USE_READLINE=yes			# command line history and completion

ALL_TARGETS=host robot doc

CPP_SRCS=gutexttowbd.cpp

.include "../../mk/whiteboard.mk"	# required for whiteboard clients
.include "../../mk/util.mk"		# required for GU utility functions
.include "../../mk/mipal.mk"		# comes last!
