#
#	$Id: 0c6e969bdbe317fbad773eef14ae869bb1253507 $
#
# GU ball tracker module Makefile
#
BIN=gureactiveController

ALL_TARGETS=host robot

CPP_SRCS=reactiveController.cpp
HDRS=reactiveController.h 

.include "../../../mk/whiteboard.mk"	# required for whiteboard clients
.include "../../../mk/mipal.mk"		# comes last!
