import os, glob

common_env = Environment()

include_paths = ['.']
lib_paths = []
common_env.Append( CPPPATH = [ os.path.abspath(p) for p in include_paths ] )
common_env.Append( CCFLAGS = ['-ggdb','-Wall', '-DDEBUG', '-D__LINUX__' ] )
common_env.Append( LINKFLAGS = ['-ggdb' ] )
#common_env.Append( CCFLAGS = ['-O3','-Wall','-DNDEBUG', '-D__LINUX__' ] )
#common_env.Append( LINKFLAGS = ['-O3' ] )

source_files = glob.glob( '*.cxx' )
object_files = [ common_env.Object( src ) for src in source_files ]

common_env.Program( 'blocks-solver', object_files )
