#! /bin/bash


#########################################################
#
#########################################################


BS=./bwstates.1/bwstates

TR=./2pddl/2pddl



$BS -s 2 -n $1 > STATES
$TR -d STATES -n $1 

rm STATES


