

distanceThreadControl.o: distanceThreadControl.cpp
	gcc -Wall -I../../../include distanceThreadControl.cpp -lstdc++ -lnxtpp -lusb -o distanceThreadControl -lpthread

clean:
	rm -f distanceThreadControl

